# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
              os: [ubuntu-latest, macOS-latest, windows-latest]  
              python-version: [3.6, 3.7, 3.8, 3.9]

        steps:
            - name: Checkout sources
              uses: actions/checkout@v1

            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python }}

            - name: Update pip
              run: |
                  python -m pip install --upgrade pip
            
            - name: Install tox
              run: |
                  python -m pip install tox tox-gh-actions
                  
            - name: Run tox
              run: |
                  python -m tox

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1.4.1
              if: matrix.python-version == 3.9 && matrix.os == 'ubuntu-latest'
              with:
                files: ./coverage.xml
                directory: ./coverage/reports/
                flags: unittests
                env_vars: OS,PYTHON
                name: codecov-umbrella
                fail_ci_if_error: true
                path_to_write_report: ./coverage/codecov_report.txt
                verbose: true